### ISSUE TITLE
Wrong closures

### ISSUE THREAD

**Issue by coret** [CLARIAH/burgerLinker#19]
Looking into the results of the closure (on CSV results of Between_B_M, Between_B_D, Between_M_M, Between_D_M, Within_B_M and Within_B_D made with  `--maxLev 3 --fixedLev` as per example) of the SAMH dataset quickly show errors, two examples:

1. Person [https://iisg.amsterdam/links/person/i-147606](https://www.goudatijdmachine.nl/sparql/resource?uri=https:%2F%2Fiisg.amsterdam%2Flinks%2Fperson%2Fi-147606) (if you don't see triples, switch from gtm to the goude-bs repository in the upper right corner).

This person is a combination of "johannes jakobus loon" and "johanna louw"? It's based on death certificate https://www.openarch.nl/smh:b7ddbde0-a8d6-8597-8541-0993c20ea6c1/ttl:civ birth certificate https://www.openarch.nl/smh:d0b6227a-af70-c2ef-3bb6-cd49eafabbea/ttl:civ and another (?) birth certificate https://www.openarch.nl/smh:9b907b90-87e4-16bf-ce39-c49cf1834df6/ttl:civ (which indicates johanna being male, error in source).

2. The graph of my person of interest "abraham johannes loon" [shown in GraphDB](https://www.goudatijdmachine.nl/sparql/graphs-visualizations?saved=e928731dba2747a894d35bc55b289346) (reload if you don't see the graph immediatly) as follows: 

![image](https://user-images.githubusercontent.com/101820/173813250-21e2502f-e30b-46d6-8c26-6da52255e80b.png)

Here the problem is the wife: partner "theodora maria kroon" (=correct) and bride "sofia theodora kroon" (=wrong).
I we look at the [marriage event](https://www.goudatijdmachine.nl/sparql/resource?uri=https:%2F%2Fwww.openarch.nl%2Fid%2Fevent_smh_604f5fe2-6e44-ec00-c44d-bd14018e14ff_Event1) and compare it with the source https://www.openarch.nl/smh:604f5fe2-6e44-ec00-c44d-bd14018e14ff/ttl:civ it's clear that the source has theodora, but the closure collapsed it to sophia?

I don't understand these "deduplication" of persons from a Levenshtein distance perspective (maxLev=3).
What happens if person 1 has 2 given names and person 2 only 1, will then only 1 given name be taken into account?
Eg.  Lev("johannes jakobus loon","joanna louw")=11 (>3) but Lev("johannes loon","joanna louw")=4 (still >3), or is it Lev("johannes","joanna")=2 and Lev("loon","louw")=2?
And is the order of given names taken into account? Lev("theodora maria kroon","sofia theodora kroon")=12 (>3) but Lev("theodora maria kroon","theodora sofia kroon")=3

**Comment by rlzijdeman** [comment]
Hi, I think we now tackled this in the text: burgerLinker focuses on finding candidate matches, not perfect matches (as in selecting the highest quality match -only-). Over mail you wrote:

` Does the sentence "when matching two individuals with multiple first names, at least two names need to be similar in order to find a candidate match; when matching individuals with multiple first names to individuals with only one first name any first name that is identical results in a match(!);" only apply to finding links (matching observations) and not the closure?
`

That is a perfect question and indeed it only applies to finding the links. The closure only provides an id for observations that are (in)directly associated to each other. (now highlighted in the readme).
