### ISSUE TITLE
schema is sometimes https:// and sometimes http://

### ISSUE THREAD

**Issue by ivozandhuis** [CLARIAH/burgerLinker#5]
Namespace schema is defined as https://schema.org/ 
In the definition of Person (and other places?) http:// is used.
Suggestion: use https:// in all situations.

**Comment by raadjoe** [comment]
I agree that it would have been better if we used httpS://schema.org instead of http://schema.org, but I understand that both are still fine (see [1](https://schema.org/docs/faq.html#19) and [2](https://github.com/schemaorg/schemaorg/issues/1914#issuecomment-387363258)).

Just to avoid re-generating our HDT datasets, I will keep using the http:// form for now, but I will add support to both forms of URLs in the next release of the tool.

**Comment by ivozandhuis** [comment]
Sounds fair. But now I have the impression that the use of http and https are mixed. The Individuals are only parsed if I use http://schema.org/Person for the class and httpS://schema.org/givenName for the property.

**Comment by raadjoe** [comment]
The tool now supports both http://schema.org/ and https://schema.org/.
